on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🧩 Insert Secrets into PHP Code
      run: |
        echo "<?php" > sub/chat/Auth/config.php
        echo "define('DB_SERVER', 'localhost');" >> sub/chat/Auth/config.php
        echo "define('DB_USERNAME', '${{ secrets.LOGIN_CHAT_NAME }}');" >> sub/chat/Auth/config.php
        echo "define('DB_PASSWORD', '${{ secrets.LOGIN_CHAT_PASS }}');" >> sub/chat/Auth/config.php
        echo "define('DB_NAME', '${{ secrets.LOGIN_CHAT_NAME }}');" >> sub/chat/Auth/config.php
        echo "" >> sub/chat/Auth/config.php
        echo "\$link = mysqli_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD, DB_NAME);" >> sub/chat/Auth/config.php
        echo "if(\$link === false){" >> sub/chat/Auth/config.php
        echo "    die('ERROR: Could not connect. ' . mysqli_connect_error());" >> sub/chat/Auth/config.php
        echo "}" >> sub/chat/Auth/config.php

        echo "<?php" > sub/chat/db.php
        echo "\$host = 'localhost';" >> sub/chat/db.php
        echo "\$db = '${{ secrets.LOGIN_CHAT_NAME }}';" >> sub/chat/db.php
        echo "\$user = '${{ secrets.LOGIN_CHAT_NAME }}';" >> sub/chat/db.php
        echo "\$password = '${{ secrets.LOGIN_CHAT_PASS }}';" >> sub/chat/db.php
        echo "" >> sub/chat/db.php
        echo "\$pdo = new PDO('mysql:host=\$host;dbname=\$db;charset=utf8', \$user, \$password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);" >> sub/chat/db.php
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: 21
        protocol: ftp
        server-dir: /gymcl.tk/
        state-name: web/.ftp.json
        exclude: |
          **/.git/**
          **/.github/**
          README.md
